POST http://localhost:11500/api/account
Content-Type: application/json

{
  "Email":"qqqqq@naver.com",
  "Password":"dsd"
}

###
POST http://localhost:11500/api/login
Content-Type: application/json

{
  "Email":"qqqqq@naver.com",
  "Password":"dsd",
  "ClientVersion":"1.0.0",
  "MasterDataVersion":"1.0.0"
}

###
POST http://localhost:11500/api/notice
Content-Type: application/json

{
  "Email":"qqqqq@naver.com",
  "AuthToken":"usy9fghdwsqepa809rrfluwhc",
  "ClientVersion":"1.0.0",
  "MasterDataVersion":"1.0.0"
}

###
POST http://localhost:11500/api/mails
Content-Type: application/json

{
  "Email":"qqqqq@naver.com",
  "AuthToken":"whe86clgl3e1e29th3r6lkdrh",
  "ClientVersion":"1.0.0",
  "MasterDataVersion":"1.0.0",
  "Page":1
}

###
POST http://localhost:11500/api/mails/70
Content-Type: application/json

{
  "Email":"qqqqq@naver.com",
  "AuthToken":"whe86clgl3e1e29th3r6lkdrh",
  "ClientVersion":"1.0.0",
  "MasterDataVersion":"1.0.0"
}

###
POST http://localhost:11500/api/attendance/check
Content-Type: application/json

{
  "Email":"qqqqq@naver.com",
  "AuthToken":"ad7mwhuez39f39t7jho8vmrij",
  "ClientVersion":"1.0.0",
  "MasterDataVersion":"1.0.0"
}

###
POST http://localhost:11500/api/mails/61/items
Content-Type: application/json

{
  "Email":"qqqqq@naver.com",
  "AuthToken":"r9t908cqpdl4lpz2x1qlocgfu",
  "ClientVersion":"1.0.0",
  "MasterDataVersion":"1.0.0"
}

###
POST http://localhost:11500/api/receipts
Content-Type: application/json

{
  "Email": "qqqqq@naver.com",
  "AuthToken": "whe86clgl3e1e29th3r6lkdrh",
  "ClientVersion": "1.0.0",
  "MasterDataVersion": "1.0.0",
  "ReceiptInfo":{
    "ReceiptId": 27,
    "ProductId": 2
  }
}