POST http://localhost:11500/api/createAccount
Content-Type: application/json

{
  "Email": "hello0716@naver.com",
  "Password": "dsd"
}

###
POST http://localhost:11500/api/login
Content-Type: application/json

{
  "Email": "hello0716@naver.com",
  "Password": "dsd",
  "ClientVersion": "1.0.0",
  "MasterDataVersion": "1.0.0"
}

###
POST http://localhost:11500/api/receiveNotice
Content-Type: application/json

{
  "Email": "hello0716@naver.com",
  "AuthToken": "4gd1c8iwkc5ac5h84iou0qn39",
  "ClientVersion": "1.0.0",
  "MasterDataVersion": "1.0.0"
}

###
POST http://localhost:11500/api/getMails
Content-Type: application/json

{
  "Email": "hello0716@naver.com",
  "AuthToken": "4gd1c8iwkc5ac5h84iou0qn39",
  "ClientVersion": "1.0.0",
  "MasterDataVersion": "1.0.0",
  "Page": 1
}

###
POST http://localhost:11500/api/getMail
Content-Type: application/json

{
  "Email": "hello0716@naver.com",
  "AuthToken": "4gd1c8iwkc5ac5h84iou0qn39",
  "ClientVersion": "1.0.0",
  "MasterDataVersion": "1.0.0",
  "MailId": 5
}

###
POST http://localhost:11500/api/checkAttendance
Content-Type: application/json

{
  "Email": "hello0716@naver.com",
  "AuthToken": "4gd1c8iwkc5ac5h84iou0qn39",
  "ClientVersion": "1.0.0",
  "MasterDataVersion": "1.0.0"
}

###
POST http://localhost:11500/api/ReceiveMailItems
Content-Type: application/json

{
  "Email": "hello0716@naver.com",
  "AuthToken": "4gd1c8iwkc5ac5h84iou0qn39",
  "ClientVersion": "1.0.0",
  "MasterDataVersion": "1.0.0",
  "MailId": 5
}

###
POST http://localhost:11500/api/receiveInAppProduct
Content-Type: application/json

{
  "Email":"hello0716@naver.com",
  "AuthToken": "4gd1c8iwkc5ac5h84iou0qn39",
  "ClientVersion": "1.0.0",
  "MasterDataVersion": "1.0.0",
  "ReceiptInfo": {
    "ReceiptId": 3,
    "ProductId": 1
  }
}

###
POST http://localhost:11500/api/enhanceItem
Content-Type: application/json

{
  "Email": "hello0716@naver.com",
  "AuthToken": "km5qigqc16ks1sdl1po5navrd",
  "ClientVersion": "1.0.0",
  "MasterDataVersion": "1.0.0",
  "PlayerItemId": 7
}