POST http://localhost:11500/api/account
Content-Type: application/json

{
  "Email":"asdf@naver.com",
  "Password":"dsd"
}

###
POST http://localhost:11500/api/login
Content-Type: application/json

{
  "Email":"asdf@naver.com",
  "Password":"dsd",
  "ClientVersion":"1.0.0",
  "MasterDataVersion":"1.0.0"
}

###
POST http://localhost:11500/api/notice
Content-Type: application/json

{
  "Email":"asdf@naver.com",
  "AuthToken":"4ky5nju6ywmlrq1x73ce01cjm",
  "ClientVersion":"1.0.0",
  "MasterDataVersion":"1.0.0"
}

###
POST http://localhost:11500/api/mails
Content-Type: application/json

{
  "Email":"asdf@naver.com",
  "AuthToken":"de0zhyml6pcv6wmrsjcbrlu5v",
  "ClientVersion":"1.0.0",
  "MasterDataVersion":"1.0.0",
  "Page":1
}

###
POST http://localhost:11500/api/mails/1
Content-Type: application/json

{
  "Email":"asdf@naver.com",
  "AuthToken":"4ky5nju6ywmlrq1x73ce01cjm",
  "ClientVersion":"1.0.0",
  "MasterDataVersion":"1.0.0"
}

###
POST http://localhost:11500/api/attendance/check
Content-Type: application/json

{
  "Email":"asdf@naver.com",
  "AuthToken":"4ky5nju6ywmlrq1x73ce01cjm",
  "ClientVersion":"1.0.0",
  "MasterDataVersion":"1.0.0"
}

###
POST http://localhost:11500/api/mails/3/items
Content-Type: application/json

{
  "Email":"asdf@naver.com",
  "AuthToken":"bpza39a00qm9fe5hex11wjul2",
  "ClientVersion":"1.0.0",
  "MasterDataVersion":"1.0.0"
}

###
POST http://localhost:11500/api/receipts
Content-Type: application/json

{
  "Email":"asdf@naver.com",
  "AuthToken": "de0zhyml6pcv6wmrsjcbrlu5v",
  "ClientVersion": "1.0.0",
  "MasterDataVersion": "1.0.0",
  "ReceiptInfo":{
    "ReceiptId": 2,
    "ProductId": 2
  }
}

###
POST http://localhost:11500/api/account-items/4/enhancements
Content-Type: application/json

{
  "Email":"asdf@naver.com",
  "AuthToken": "bpza39a00qm9fe5hex11wjul2",
  "ClientVersion": "1.0.0",
  "MasterDataVersion": "1.0.0"
}